### ISSUE TITLE
Copy-paste event listeners

### ISSUE THREAD

**Issue by tomastrivino** [geogebra/integration#2]
Hello,
I'm embedding a Geogebra Applet using the JS SDK. **Shortcuts such as CTRL+C, CTRL+V do not work.**
I tried focusing the div containing the application but it didn't work. I couldn't find anything related to copying and pasting elements in the API either. Is there any way to listen to CTRL+C and CTRL+V events in the applet then? 

I would appreciate some help! Thanks!

**Comment by murkle** [comment]
Please ask on Reddit and explain what you're trying to do overall
